# Generated by Django 5.1.4 on 2025-03-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='user',
            new_name='owner',
        ),
    ]
